// src/renderer/src/App.svelte
<script lang="ts">
    let text = 'Frissítés keresése'
    let loadtext = true
    let loading = true
    let data: { username: string; id: string } = {
        id: '2d27308ccd8a42b0badcbf6d5d2eb59c',
        username: 'HVCsano',
    }
    window.electron.ipcRenderer.on('update-van', () => {
        text = 'Frissítés letöltésének megkezdése'
    })
    window.electron.ipcRenderer.on('update-tölt', (_ev, arg) => {
        text = `Frissítés letöltése ${arg}%`
    })
    window.electron.ipcRenderer.on('update-nincs', () => {
        text = 'Nincs frissítés'
    })
    window.electron.ipcRenderer.on('setloadtext', (_ev, arg) => {
        text = arg
    })
    window.electron.ipcRenderer.on('hideloadtext', () => {
        loading = false
    })
    window.electron.ipcRenderer.on('getdata', (_ev, arg) => {
        data = arg
    })
</script>

{#if loading}
    <div class="h-screen flex">
        <div class="m-auto text-center">
            <div class="lds-ripple">
                <div></div>
                <div></div>
            </div>
            {#if loadtext}
                <h1 class="text-white font-bold">{text}</h1>
            {/if}
        </div>
    </div>
{:else}
    <div class="bg-gray-900 flex justify-end items-center gap-4">
        <h1 class="font-bold text-xl text-white">
            {data.username}
        </h1>
        <img src={`https://mc-heads.net/avatar/${data.id}/32`} alt="" />
    </div>
    <div class="flex gap-4 mt-4 ml-4">
        <div class="bg-gray-900 w-[200px] h-[200px] text-center">
            <h1 class="font-bold text-xl bg-gray-600 mb-10 text-white">
                Ampix SMP
            </h1>
            <button
                class="bg-green-500 text-white font-bold m-auto uppercase p-2 rounded-xl hover:bg-green-700 transition-all duration-200"
                >Játék</button
            >
        </div>
    </div>
{/if}

// src/App.vue
<script setup lang="ts">
let page = 'welcome'
</script>

<template>
    <div class="grid 2xl:grid-cols-8 grid-cols-4">
        <div class="bg-slate-500 h-screen grid">
            <div class="flex flex-col justify-center items-center">
                <img
                    src="https://cdn.discordapp.com/avatars/440489260345458690/c85d6d2424e4266fb4d3196acdeb422e?size=1024"
                    alt="Profpic"
                    class="rounded-full w-fit h-fit px-5 drop-shadow-xl mt-3"
                />
                <h1 class="text-white font-bold text-3xl drop-shadow-xl">
                    HVCsano
                </h1>
            </div>
            <div
                class="text-white text-3xl text-center child:py-5 child:bg-slate-600 flex flex-col justify-end child:mb-5 child:cursor-pointer font-bold child-hover:bg-slate-400 child-hover:-translate-y-2 child:mx-3 child:rounded-xl child:drop-shadow-xl child:transition-all child:duration-200"
            >
                <button>Kezdőlap</button>
                <button>Hírek</button>
                <button>Minecraft</button>
                <button>Beállítások</button>
            </div>
        </div>
        <div
            v-if="page === 'welcome'"
            class="w-full col-span-3 m-auto text-center items-center justify-center 2xl:col-span-7"
        >
            <h1 class="text-white text-5xl">Üdvözöllek az új Ampix Appban!</h1>
            <h2 class="text-gray-300 text-xl">
                Mielőtt bármit is csinálnál, egy pár dolgot be kellene
                állítanod!
            </h2>
            <button
                class="text-white bg-blue-600 text-4xl py-1 px-3 rounded-xl font-bold m-2 hover:bg-blue-400 hover:text-gray-100 transition-all"
            >
                Kezdjük
            </button>
        </div>
    </div>
</template>
